### ISSUE TITLE
reference to nightly not guarded with #[cfg(nightly)]

### ISSUE THREAD

**Issue by tstack** [yehuthi/round_mult#1]
The following import fails on non-nightly rustc versions:

https://github.com/yehuthi/round_mult/blob/ef7a24d31d017b1f1a9dea880bca00538ab4e7aa/src/lib.rs#L8

```
error[E0432]: unresolved import `nzp::LanesMult`
 --> /Users/tstack/.cargo/registry/src/github.com-1ecc6299db9ec823/round_mult-0.1.2/src/lib.rs:8:28
  |
8 | pub use nzp::{NonZeroPow2, LanesMult};
  |                            ^^^^^^^^^ no `LanesMult` in `nzp`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `round_mult` due to previous error
```

The reference to `LanesMult` in the `nzp` module is guarded with a `#[cfg(nightly)]`, but the same is not done here.

**Comment by yehuthi** [comment]
Merged and published.

Apologies for the delay and thank you both!
